.\" Manpage for sort_all_pfiles.
.TH man 1 "06 May 2010" "1.0" "nuseradd man page"
.SH NAME
sort_all_pfiles : Code to take a list of pfiles and sort them into folders. It also tries to sort some acessory files. 

.SH DESCRIPTION
sort_all_pfiles is a bash script designed to call pfile_info and use that to put files into folders by exam and series number. 

.SH EXAMPLES
Navigate to the directory with the unsroted pfiles and call "sort_all_pfiles"

.SH OPTIONS
Code has no options.

.SH SEE ALSO
pfile_info
index_pfiles 
pfile_bundle

.SH BUGS

.SH AUTHOR
Initial author - Kevin Johnson (kmjohnson3@wisc.edu)

.SH COPYRIGHT
Specify your copyright information.

